version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "🦈"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/.docker"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "🐳"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "🐙"
