diagnostic_aggregator:
  ros__parameters:
    analyzers: ['bluerov2']

    bluerov2:
      type: diagnostic_aggregator/AnalyzerGroup
      path: bluerov2
      analyzers: ['factor_graph_node', 'navsat_preprocessor_node']

      factor_graph_node:
        type: diagnostic_aggregator/GenericAnalyzer
        path: 'factor_graph_node'
        regex: ['.*factor_graph_node.*bluerov2.*']
        find_and_remove_prefix: ['factor_graph_node: [/bluerov2]', 'factor_graph_node_tm: [/bluerov2] ']
        timeout: 5.0

      navsat_preprocessor_node:
        type: diagnostic_aggregator/GenericAnalyzer
        path: 'navsat_preprocessor_node'
        regex: ['.*navsat_preprocessor_node.*bluerov2.*']
        find_and_remove_prefix: ['navsat_preprocessor_node: [/bluerov2] ']
        timeout: 5.0

      hsd_commander_node:
        type: diagnostic_aggregator/GenericAnalyzer
        path: 'hsd_commander_node'
        regex: ['.*hsd_commander_node.*bluerov2.*']
        find_and_remove_prefix: ['hsd_commander_node: [/bluerov2] ']
        timeout: 5.0
