diagnostic_aggregator:
  ros__parameters:
    analyzers: ['bluerov2']

    bluerov2:
      type: diagnostic_aggregator/AnalyzerGroup
      path: bluerov2
      analyzers: ['factor_graph_node', 'origin_manager_node', 'waypoint_follower_node']

      factor_graph_node:
        type: diagnostic_aggregator/GenericAnalyzer
        path: 'factor_graph_node'
        regex: ['.*factor_graph_node.*bluerov2.*']
        find_and_remove_prefix: ['factor_graph_node: [/bluerov2]', 'factor_graph_node_tm: [/bluerov2] ']
        timeout: 5.0

      origin_manager_node:
        type: diagnostic_aggregator/GenericAnalyzer
        path: 'origin_manager_node'
        regex: ['.*origin_manager_node.*bluerov2.*']
        find_and_remove_prefix: ['origin_manager_node: [/bluerov2] ']
        timeout: 5.0

      waypoint_follower_node:
        type: diagnostic_aggregator/GenericAnalyzer
        path: 'waypoint_follower_node'
        regex: ['.*waypoint_follower_node.*bluerov2.*']
        find_and_remove_prefix: ['waypoint_follower_node: [/bluerov2] ']
        timeout: 5.0
