# Copyright (c) 2026 BYU FROST Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM snelsondurrant/cougars:base

ARG DEBIAN_FRONTEND=noninteractive
ARG DOCKER_USER=frostlab-docker
ARG USER_UID=1000
ARG USER_GID=1000

SHELL ["/bin/bash", "-c"]

ENV DOCKER_USER=$DOCKER_USER \
    PATH="$PATH:/home/$DOCKER_USER/.local/bin"

RUN groupadd --gid $USER_GID "$DOCKER_USER" \
    && useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash "$DOCKER_USER" \
    && usermod -aG sudo "$DOCKER_USER" \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
    && echo 'source /opt/ros/humble/setup.bash' >> /home/$DOCKER_USER/.bashrc \
    && echo '[ -f ~/ros2_ws/install/setup.bash ] && source ~/ros2_ws/install/setup.bash' >> /home/$DOCKER_USER/.bashrc \
    && touch /home/$DOCKER_USER/.hushlogin \
    && mkdir -p /home/$DOCKER_USER/ros2_ws/src \
    && chown -R $DOCKER_USER:$DOCKER_USER /home/$DOCKER_USER

# Install development tools
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
    vim nano tmux xclip python3-pip python3-venv \
    x11-apps x11-utils x11-xserver-utils xauth

# Install Python development tools
USER $DOCKER_USER
RUN --mount=type=cache,target=/home/$DOCKER_USER/.cache/pip,uid=1000,gid=1000 \
    pip3 install --upgrade vcstool pre-commit asciimatics Pillow

# Install tmux plugins
RUN git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
COPY --chown=$DOCKER_USER:$DOCKER_USER docker/.tmux.conf /home/$DOCKER_USER/.tmux.conf
RUN ~/.tmux/plugins/tpm/bin/install_plugins || true

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
